### ISSUE TITLE
Mapeamento de Tipos de Processos: Cadastrar/Remover unidades do órgão externo

### ISSUE THREAD

**Issue by caduvieira** [supergovbr/mod-sei-pen#251]

**Comment by euviniciusmendonca** [comment]
O nome da funcionalidade foi alterado.

O protótipo atual é o seguinte: https://www.figma.com/file/w2MIP7290Ms7VIktsbTGdX/Tramita---Mapeamento-de-Tipo-de-Processo?type=design&node-id=9-3&mode=design&t=L4HtvO1LR6mNKMjy-0.

**Comment by Mauro1706** [comment]
Segue evidência da funcionalidade:

https://github.com/supergovbr/mod-sei-pen/assets/83025710/fd161f20-cfca-407f-b53b-d9a2f4710966

**Comment by davidnascimento1618** [comment]
Inconsistências encontradas conforme [comentário](https://github.com/supergovbr/mod-sei-pen/issues/250#issuecomment-1664918497) da _issue_ 250.

**Comment by davidnascimento1618** [comment]
Inconsistências encontradas conforme [comentário](https://github.com/pengovbr/mod-sei-pen/issues/250#issuecomment-1672557121) da _issue_ 250.

**Comment by davidnascimento1618** [comment]
Foi verificado que o sistema está retornando todos os registros, ao digitar o valor "0" (que não consta em parte dos textos dos órgãos), utilizando os filtros de pesquisa nos campos: 'Órgão Origem' e 'Órgão Destino', como é exibido no _.gif_ abaixo:

![Campos de órgão de origem e destino estão trazendo resultados na pesquisa com o número 0](https://github.com/pengovbr/mod-sei-pen/assets/87980947/cdbdbaf4-eed4-419b-bb13-d43e335aaf86)

**Comment by Mauro1706** [comment]
Realizado correção de consulta por 0.

https://github.com/pengovbr/mod-sei-pen/assets/83025710/7d65bf99-3698-4366-844a-449a4243d8c8

**Comment by davidnascimento1618** [comment]
Prezado @Mauro1706, corrigir os conflitos mencionados [aqui](https://github.com/pengovbr/mod-sei-pen/pull/323#pullrequestreview-1639053599).

**Comment by davidnascimento1618** [comment]
Prezado @Mauro1706, favor corrigir os [problemas](https://github.com/pengovbr/mod-sei-pen/pull/323#pullrequestreview-1686516474) encontrados no _pull request_ em questão.

**Comment by davidnascimento1618** [comment]
Alguns pontos que foram acordados na agenda do dia **24/10/2023**:

Para a tela de 'Relacionamento entre Orgãos':

- [ ] 1. Manter o botão superior com a nomenclatura "Novo";
- [ ] 2. O ícone de importação só será exibido se ainda não tiver sido importado o arquivo _.csv_, senão, o botão de mapeamento será exibido, para que seja levado à tela de 'Mapeamento de Tipos de Processo';
- [ ] 3. Ao clicar sobre o ícone de importação, exibir um _modal_, com _select_ de arquivo para importação, uma vez carregado o arquivo, o sistema deverá validar o seu teor e exibir um _preview_ do seu conteúdo para confirmação do usuário, quando este clicar em salvar, importar o teor do arquivo;
- [ ] 4. O ícone de 'Mapeamento' é o mesmo que consta na seção 'Ações' da tela de 'Tabelas de Assuntos';
- [ ] 5. A coluna 'Tipo de Processo Destino' trará todos os tipos de processos existentes no sistema, enquanto o 'Tipo de Processo Origem' terão apenas os tipos de processos que foram importados, ou seja, os que constam no arquivo _.csv_;

**Comment by davidnascimento1618** [comment]
Prezado @Mauro1706, corrigir os seguintes problemas encontrados:

- [ ] **1.** O comportamento descrito no item **2** [desta lista](https://github.com/pengovbr/mod-sei-pen/issues/251#issuecomment-1779532310), não foi implementado;
- [ ] **2.** Corrigir o título do _modal_ referente ao _preview_ , o certo seria: _"Pré-visualização da Importação de Tipos de Processo"_ ao invés de _"Pré-visualização de Improtar Tipos de Processos"_;
- [ ] **3.** Descrições apresentando caracteres inválidos em tipos de processo que contém acentuação;
- [ ] **4.** A descrição da coluna do _modal_ deveria ser: 'Tipo de Processo' ao invés de 'Nome';
- [ ] **5.** Caso o arquivo seja relativamente grande (contenha em torno de 15 tipos de processos), os tidos de processo não são comportados dentro do _modal_, o ideal era que tivesse uma lista corrida com uma barrinha de rolagem na lateral ou outra maneira pela qual o usuário pudesse visualizar todos os tipos de processo que foram importados do arquivo _.csv_;

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/ea7a0c6d-0556-4adf-8044-d93419284959)

- [ ] **6.** O ícone descrito no item **4** [desta lista](https://github.com/pengovbr/mod-sei-pen/issues/251#issuecomment-1779532310), não foi implementado.

**Comment by davidnascimento1618** [comment]
@Mauro1706, segue o ícone de importação para que seja incluído na seção de 'Ações':

![icone-importacao](https://github.com/pengovbr/mod-sei-pen/assets/87980947/2e9d294a-fae3-4d4d-bb1f-cbb7f06fdb26)

**Comment by davidnascimento1618** [comment]
Prezado @Mauro1706, corrigir os seguintes itens abaixo:

- [ ] **1.** Foi identificado que ao excluir um relacionamento entre órgãos pelo qual não houve importação do arquivo ._csv_, o sistema está apresentando o seguinte erro abaixo:

_"Cannot delete or update a parent row: a foreign key constraint fails (`sei`.`md_pen_map_tipo_processo`, CONSTRAINT `fk_md_pen_mapeamento_orgao` FOREIGN KEY (`id_map_orgao`) REFERENCES `md_pen_orgao_externo` (`id`))"_

Esta mensagem deveria estar tratada ou mesmo nem sequer aparecer o ícone de exclusão de mapeamento entre órgãos quando houvesse uma importação;

![Erro ao tentar excluir um mapeamento que já foi importado os tipos de processo](https://github.com/pengovbr/mod-sei-pen/assets/87980947/02dc9b8f-777c-4e92-9f9d-f1e86c5cb970)

- [ ] **2.** Outro ponto que deve ser corrigido, seria no tocante a mensagem de sucesso de cadastro de relacionamento entre órgãos, se ao realizar o cadastro e logo em seguida tentar importar um arquivo _.csv_, a mensagem está ficando por cima do _modal_ de pré-visualização;

![Mensagem de sucesso de cadastro de relacionamento entre órgãos pro cima do modal](https://github.com/pengovbr/mod-sei-pen/assets/87980947/bb0a59d2-2e97-463c-912f-48c18abdc343)

- [ ] **3.** Corrigir o que encontra-se apontado neste item [aqui](https://github.com/pengovbr/mod-sei-pen/pull/323#pullrequestreview-1737960615);

- [ ] **4.** Seguir a recomendação descrita no item **2** desse [comentário](https://github.com/pengovbr/mod-sei-pen/issues/257#issuecomment-1829187413) para separar os roteiros de testes.

**Comment by Mauro1706** [comment]
tarefa movida de sprint 29 para sprint 30

**Comment by sergioadao** [comment]
@mauro...Prolema de visualização na tela de pre-visualização de exportação de tipo de processo. Versão 3.1.7.
Segue vídeo. 
![problema_tela_previsialização_exportacao_11-12-2023 10-35](https://github.com/pengovbr/mod-sei-pen/assets/87815724/5343f14b-b0eb-48b3-98d5-156b7cf33223)

**Comment by sergioadao** [comment]
@Mauro1706 .....Segue menagem de erro que ocorre no processo de exportação do tipo de processo...

![problema_processo_exportacao_tipo_processo_11-12-2023 10-49](https://github.com/pengovbr/mod-sei-pen/assets/87815724/203b74f5-5e6b-431c-9a30-aaace4da1e55)

**Comment by sergioadao** [comment]
@Mauro1706 ....segue vídeo com erro apresentado o processo de exportação. A exportação não é de toda tabela, apenas 10 itens. 
![problema_processo_exportacao_tipo_processo_11-12-2023 10-49](https://github.com/pengovbr/mod-sei-pen/assets/87815724/07015db6-ed5a-4005-a5fb-fe5314cf5a18)

**Comment by sergioadao** [comment]
Bom dia @Mauro1706 .....testes tealizados no ambiente SEI3/MYSQL......segue inconsistência encontrada no envio de processos. Quando no destino existe um mapeamento processo cadastrado...este mapeamento não está sendo obedecido. Abaixo seguem 2 vídeos...o primeiro apresenta o processo sendo gerado no destino e o segundo o recebimento deste mesmo processo, com mapeamento realizado e não sendo obedecido.

Fico a disposição.


![envio_processo_mapeamento_tipo_processo_sei3-mysql](https://github.com/pengovbr/mod-sei-pen/assets/87815724/4ad25e4f-78c0-40db-8b4e-4e90f17eff55)

![erro_recebimento_mapeameto_tipo_processo_sei3-mysql](https://github.com/pengovbr/mod-sei-pen/assets/87815724/8609fd37-b8e8-41c1-a70d-329062f2c1d9)

**Comment by sergioadao** [comment]
Bom dia @Mauro1706 ......no ambiente SEI3/MYSQL....existe um erro já reportado no processo de exportação do arquivo CSV....
Contudo, fiz um teste de importação de um arquivo csv (tipo de processos já existente). O primeiro procedimento funcionou perfeitamente. A inconsistência encontrada aparece quando.....um tipo de processo é removido da lista e é necessário recarregá-lo......a partir do segundo procedimento de importação do csv os registros não existentes na tabela do sistema são carregados, porém ficam no fim da lista da tabela de processos...permitindo ao usuário entender....de maneira equivocada....que a carga na foi realizada.....abaixo segue vídeo que apresenta a inconsistênia......

![importacao_csv_processo_nao_classificado_sei3-mysql](https://github.com/pengovbr/mod-sei-pen/assets/87815724/41bde3cd-f88c-4cec-9884-cb70c2632f61)

**Comment by mateussbh** [comment]
@sergioadao, favor informar se os erros apontados no SEI3 desta issue foram sanados. Obrigado.

**Comment by sergioadao** [comment]
@mateussbh e  @Mauro1706 problema de visualização do mapeamento do tipo de processo resolvido.

**Comment by mateussbh** [comment]
Funcionalidade testada com sucesso nas versões sei-oficial (antigo super), nos bancos mysql, oracle e sqlserver, no sei 4, versões de banco mysql, oracle e sqlserver, e sei3, versão de banco mysql.

Foi seguido um roteiro de testes, conforme documento (https://mtegovbr.sharepoint.com/:o:/s/Super.br/EtqPl3ipk2xOpTesIG25hwcBk1YxDoLax5bhcRBH18-b9w?e=uy8UtN), para registrar os casos de testes testados, e em quais versões do sistema e banco de dados.


Issues que fazem parte do pacote da funcionalidade "mapeamento de tipo de processo":

**Mapeamento de Tipos de Processos: Cadastro de Relacionamento entre Órgãos**
	https://github.com/pengovbr/mod-sei-pen/issues/250 
	
**Mapeamento de Tipos de Processos: Relacionamento entre Órgãos**
	https://github.com/pengovbr/mod-sei-pen/issues/251 

**Mapeamento de Tipos de Processos: Mapeamento de Tipo de Processo - [Nome do órgão origem]**
	https://github.com/pengovbr/mod-sei-pen/issues/324 
	
**Mapeamento de Tipos de Processos: Ação Reativar o mapeamento de órgão externo**
	https://github.com/pengovbr/mod-sei-pen/issues/253 

~~**Mapeamento de Tipos de Processos: Importar Tipos de Processos para mapeamento**
	https://github.com/pengovbr/mod-sei-pen/issues/257~~ [DUPLICADA]
	
**Mapeamento de Tipos de Processos: Importar no destinatário o arquivo com Tipos de Processo do remetente**
	https://github.com/pengovbr/mod-sei-pen/issues/254 

~~**Mapeamento de Tipos de Processos: Exportar Tipos de processos em arquivo**
	https://github.com/pengovbr/mod-sei-pen/issues/256~~  [DUPLICADA]
	
**Mapeamento de Tipos de Processos: Exportar Tipos de Processo do órgão remetente**
	https://github.com/pengovbr/mod-sei-pen/issues/252 

**Mapeamento de Tipos de Processo: Exclusão de Tipos de Processos Mapeados**
	https://github.com/pengovbr/mod-sei-pen/issues/384 

**Mapeamento de Tipos de Processos: Aplicar mapeamento automático de t. processo no recebimento**
	https://github.com/pengovbr/mod-sei-pen/issues/255

**Comment by euviniciusmendonca** [comment]
Após a validação negocial, a DIVIN liberou a release da versão 3.5.0 na qual está incluída a funcionalidade Mapeamento de Tipo de Processos.
